apiRules:
- exclude:
    uidRegex: ^DisCatSharp\.Hosting\.Tests$
- exclude:
    uidRegex: ^DisCatSharp\.Tests$
- exclude:
    uidRegex: ^DisCatSharp\.Configuration\.Tests$
- include:
    uidRegex: ^DisCatSharp
- exclude:
    uidRegex: ^Newtonsoft\.Json$
