apiRules:
- exclude:
    uidRegex: ^System\.Collections\.Immutable$
- exclude:
    uidRegex: ^System\..*$
- exclude:
    uidRegex: ^DSharpPlusNextGen\.RingBuffer.*$
- exclude:
    uidRegex: ^DSharpPlusNextGen\.Base(WebSocket|Udp)Client.*$
- exclude:
    uidRegex: ^DSharpPlusNextGen\.HttpRequestMethod.*$
- exclude:
    uidRegex: ^DSharpPlusNextGen\.VoiceNext\.Codec.*$
attributeRules:
- exclude:
    uidRegex: ^System\.Collections\.Immutable$
    type: Namespace
