name: "Build Library"

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dotnet: [7.x]
    runs-on: ${{ matrix.os }}
    name: Build library
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build library
      run: dotnet build -c Release -v normal --no-restore
    - name: Test library
      run: dotnet test -v normal -c Release --no-restore --no-build
