name: "Build Library"

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: true

jobs:
  build:
    timeout-minutes: 6
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Build library
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: |
          7.0.203
          6.x
    - name: Build library
      run: dotnet build -c Release -v normal DisCatSharp.sln
    - name: Test library
      run: dotnet test -v normal -c Release --no-restore --no-build DisCatSharp.sln
