name: Docs Preview

on:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build docs
        uses: Amadevus/pwsh-script@v2.0.1
        id: docs
        with:
          script: .\ci_oneclick-rebuild-docs.ps1
      
      - run: echo '${{ steps.docs.outputs.result }}'

      - name: Archive Docs
        uses: actions/upload-artifact@v2
        with:
          name: preview-docs
          path: dcs-docs-preview.tar.xz
