name: "Test Documentation"
on:
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build documentation
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token:  ${{ secrets.NYUW_TOKEN_GH }}
        ref: ${{ github.ref_name }}
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 7.x
    - name: Restore packages
      run: dotnet restore
    - name: Build library
      run: dotnet build -c Release
      continue-on-error: true
    - name: Build Docs
      shell: pwsh
      run: ./rebuild-docs.ps1 -DocsPath "./DisCatSharp.Docs" -Output "." -PackageName "dcs-docs-preview"
    - name: Upload packed docs
      uses: actions/upload-artifact@v3
      with:
        name: dcs-docs-preview.zip
        path: dcs-docs-preview.zip
        retention-days: 30
  test_documentation:
    runs-on: ubuntu-latest
    name: Test documentation
    needs: build
    steps:
    - name: Checkout docs repository
      uses: actions/checkout@v3
      with:
        repository: Aiko-IT-Systems/DisCatSharp.Docs
        token: ${{ secrets.NYUW_TOKEN_GH }}
    - name: Purge old docs
      shell: pwsh
      run: Get-ChildItem -Exclude .git* | Remove-Item -Recurse -Force
    - name: Download packed docs
      uses: actions/download-artifact@v3
      with:
        name: dcs-docs-preview.zip
    - name: Extract new docs
      run: unzip dcs-docs-preview.zip -d .
    - name: Deleze zip
      run: rm dcs-docs-preview.zip
    - name: Add .htaccess
      run: rm -f .htaccess && wget https://gist.githubusercontent.com/Lulalaby/8a032d0ddebb9125691094edc67b6593/raw/8ba47fc2b8959aa43d66da95b5e56e0802a22dd6/.htaccess
    - name: Set access rights
      run: sudo chmod 777 -R .
    - name: Commit changes
      run: |
        git config user.name NyuwBot
        git config user.email nyuw@aitsys.dev
        git add .
        git commit -m "Test-Docs update (https://github.com/${{github.repository}}/commit/${{github.sha}})"
        git push -f
