name: "Build"
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  setup:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        dotnet: [6.0.202]
    runs-on: ${{ matrix.os }}
    name: Setup .NET
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Restore dependencies
      run: dotnet restore
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Build library
    needs: [setup]
    steps:
    - name: Build library
      run: dotnet build --no-restore
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Test library
    needs: [setup, build]
    steps:
    - name: Test library
      run: dotnet test --no-build --verbosity normal
