name: Label PRs

on:
  pull_request_target:
    types:
      - opened

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: srvaroa/labeler@v0.9
      env:
        GITHUB_TOKEN: "${{ secrets.NYUW_TOKEN_GH }}"
