name: "Tweet Releases"
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: "Get Release Tag"
        run: |
          RELEASE_TAG=$(curl https://api.github.com/repos/Aiko-IT-Systems/DisCatSharp/releases/latest | jq -r '.tag_name')
      - name: Tweet release
        uses: ethomson/send-tweet-action@v1
        with:
          consumer-key: ${{ secrets.DCS_CONSUMER_KEY }}
          consumer-secret: ${{ secrets.DCS_CONSUMER_SECRET }}
          access-token: ${{ secrets.DCS_ACCESS_TOKEN_KEY }}
          access-token-secret: ${{ secrets.DCS_ACCESS_TOKEN_SECRET }}
          status: "$RELEASE_TAG is here! Checkout the GitHub Page for changelog regarding the $RELEASE_TAG Release: github.com/Aiko-IT-Systems/DisCatSharp/releases/tag/$RELEASE_TAG"
